version: 2
updates:
- package-ecosystem: cargo
  directory: "/hello-world"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - ffflorian
- package-ecosystem: cargo
  directory: "/fibonacci"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - ffflorian
