name: Test all projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Test all projects
        run: ./bin/test-all.sh
